dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-09/run.sh |
  bash
notofocations:
  slack:
    rooms:
      secure: oBop33TMVZIjhpbuGde3l8u+KnciTe3qTyv2iqreHNCkSXnrEx34BCEydDlg563VcW2HBnR9d0VNNzFpWAXPPpBmU7c6roS2Zhhq9YqFtRxPxc8tTeqPeKtOfpUyU2/ELONJN7W4skJKns/wrZu+Q2kzCmXjM7xC8FD8QOM+exLJJe9IFyGhKqSUe6yTZQPKeQ9unt6PJ5qpkseA9jImuBqj7g7cRkKs8Tqhhet8DsHHzdG5+zuVeSgetSaEr8gLbfX7Wt58n3mqXAvpbu1RWU810/qN/1cI1tFHJh7GR8DMVP7BmEZ08rget/a6uGuKQFmP2R/Kz1k0OQAFztVsE0AAUQN+On1RAsWyL5bQnluYQOsZwBa8a7lWzYngifNb4NXWufjxrFJax7g2KamDcvKHCPzVPhSsbmD6X5RDbgzOCdwjDFfNsTTR1yuIvYLfqSQDm0Fd6P1037WBbR5RJ00fvYDeIzbwQfqmojoX8xwm06h2/aCtxIvojYUlrc5fGfj+hU6gdVYlrmSA+s9T/ss8zBya0N4CAvUplB0lAvQRQt9zhQRmAuAY8hfRoTmXJyI3F+Ss2n587zLtA+oejRRAWqc1hEGXZzp1XILWJu2OcPA6aD7Evc7oy4jlVRqzQtzZURD7T9io8ONdygG4ulYK9UpXRMsfZDe+rSlO3qs=
